# Template for all the secrets stored in the per-environment
# config/credentials/${env}.yml.enc files. This can be used to
# generate a new encrypted credentials store with it's own key,
# for either a new environment or to overwrite an existing environment.
database:
  username:
  password:
